[default]
    DEBUG = false
    LEVEL_NAME = "DEBUG"

[development]
    DEBUG = true

    [development.logs]
        LEVEL_NAME = "DEBUG"
        FORMAT = '[%(asctime)s] #%(levelname)-8s %(filename)s:%(lineno)d - %(name)s - %(message)s'

    [development.bot]
        PARSE_MODE = 'HTML'

    [development.postgres]
        NAME = 'postgres'
        HOST = 'localhost'
        PORT = 5432
        USER = 'postgres'
        PASSWORD = 'postgres'

    [development.google]
        SPREADSHEET_ID = "1lOULWGS1dNpw_E7TYTtJneT2Ie05UAqEGgpi2-i1XnY"